### ISSUE TITLE
VeCanSetup unable to install on RaspberryPi

### ISSUE THREAD

**Issue by JensGumball** [kwindrem/VeCanSetup#30]
Hello, I always get the following error when installing 
login as: root
root@192.168.0.55's password:
Last login: Tue Oct 31 14:39:54 2023 from 192.168.0.38
root@raspberrypi2:~# wget -qO - https://github.com/kwindrem/VeCanSetup/archive/current.tar.gz | tar -xzf - -C /data
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
root@raspberrypi2:~#
please help

**Comment by kwindrem** [comment]
That statement is out of date. Replace current with latest.

I'll correct the documentation on the next update.

Most people use SetupHelper's PackageManager to install packages which is why I did not notice this. You do need SetupHelper in place in /data for VeCanSetup/setup to run anyway. But you do not need to install it and have PackageManager running if you choose to manage packages manually.
